apiVersion: v1
kind: ConfigMap
metadata:
  name: istiod-values
  namespace: istio-system
data:
  values.yaml: |
    meshConfig:
      mode: ambient
      enablePrometheusMerge: false
      discoverySelectors:
        - matchLabels:
            istio-injection: enabled
      defaultConfig:
        environment:
          ambient:
            enablesMtls: true

    pilot:
      env:
        PILOT_ENABLE_AMBIENT: "true"
        CA_TRUSTED_NODE_ACCOUNTS: "istio-system/ztunnel"

    ambient:
      enabled: true

