apiVersion: v1
kind: ConfigMap
metadata:
  name: ztunnel-values
  namespace: istio-system
data:
  values.yaml: |
    meshConfig:
      defaultConfig:
        proxyMetadata: {}
      discoverySelectors:
        - matchLabels:
            istio-injection: enabled


