apiVersion: v1
kind: ConfigMap
metadata:
  name: ambient-values
  namespace: ambient
data:
  values.yaml: |
    global:
      variant: distroless
    
    # Overrides for the `istiod-remote` dep
    istiod:
      enabled: true
      profile: ambient
    
    # Overrides for the `ztunnel` dep
    ztunnel:
      profile: ambient
    
    # Overrides for the `cni` dep
    cni:
      profile: ambient

